twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        img_path: '../images/'
        css_path: '../../web/css/'
        js_path : '../../web/js/'
        fc_path : '../../node_modules/fullcalendar/'
        BScss_path: 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'
        BSjs_path : 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'
        jQuery  : 'https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js'
        jQuery2 : 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'
        jQuery1 : 'https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js'
