<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\JeuxController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/ParentController.php';
include_once $this->targetDirs[3].'/src/Controller/JeuxController.php';

$this->services['App\\Controller\\JeuxController'] = $instance = new \App\Controller\JeuxController();

$instance->setContainer(($this->privates['.service_locator.6lw4l8c'] ?? $this->load('get_ServiceLocator_6lw4l8cService.php'))->withContext('App\\Controller\\JeuxController', $this));

return $instance;
