<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'compte' => [[], ['_controller' => 'App\\Controller\\SecurityController::connecte'], [], [['text', '/compte']], [], []],
    'newUser' => [[], ['_controller' => 'App\\Controller\\SecurityController::newUser'], [], [['text', '/newUser']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'main' => [[], ['_controller' => 'App\\Controller\\AccueilController::main'], [], [['text', '/']], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::main'], [], [['text', '/accueil']], [], []],
    'jeux' => [[], ['_controller' => 'App\\Controller\\JeuxController::main'], [], [['text', '/jeux']], [], []],
    'calendrier' => [[], ['_controller' => 'App\\Controller\\CalendrierController::main'], [], [['text', '/calendrier']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::main'], [], [['text', '/contact']], [], []],
    'mail' => [[], ['_controller' => 'App\\Controller\\ContactController::envoi'], [], [['text', '/mail']], [], []],
];
