vide:
    path: /
    controller: App\Controller\AccueilController::main
main:
    path: /main
    controller: App\Controller\AccueilController::main
accueil:
    path: /accueil
    controller: App\Controller\AccueilController::main
jeux:
    path: /jeux
    controller: App\Controller\JeuxController::main
calendrier:
    path: /calendrier
    controller: App\Controller\CalendrierController::main
contact:
    path: /contact
    controller: App\Controller\ContactController::main
mail:
    path: /mail
    controller: App\Controller\ContactController::envoi
#login:
#    path: /login
#    controller: App\Controller\LogController::main
#login_check:
#    path: /login_check
#logout:
#    path: /logout