accueil:
    path: /accueil
    controller: App\Controller\AccueilController::main
mail:
    path: /mail
    controller: App\Controller\ContactController::envoi
#login:
#    path: /login
#    controller: App\Controller\LogController::main
#login_check:
#    path: /login_check
#logout:
#    path: /logout