# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Service du discord bot:run
    App\Service\ServiceDiscord:
       arguments:
           $token: '%env(TOKEN)%'
           $botId: '%env(BOT_ID)%'
           $idParties: '%env(ID_PARTIES)%'
           $idAnnonces: '%env(ID_ANNONCES)%'
           $idVotes: '%env(ID_VOTES)%'

    # Création d'une date app:creer
    App\Command\CommandeCreer:
       arguments:
           $token: '%env(TOKEN)%'
           $botId: '%env(BOT_ID)%'

    # Inscription a une séance app:inscription
    App\Command\CommandeParticiper:
       arguments:
           $token: '%env(TOKEN)%'
           $botId: '%env(BOT_ID)%'

    # Désinscription d'une séance app:desinscription
    App\Command\CommandeDesinscription:
       arguments:
           $token: '%env(TOKEN)%'
           $botId: '%env(BOT_ID)%'

    # Affichage des prochains evts app:maj
    App\Command\CommandeMaj:
       arguments:
           $token: '%env(TOKEN)%'
           $botId: '%env(BOT_ID)%'

    # Lister des jeux sur Discord app:lister_jeux
    App\Command\CommandeListerJeux:
       arguments:
           $token: '%env(TOKEN)%'
           $botId: '%env(BOT_ID)%'

    # Mise à jour ou création du compte sur le site app:email
    App\Command\CommandeEmail:
       arguments:
           $token: '%env(TOKEN)%'
           $botId: '%env(BOT_ID)%'

    # Affichage des noms des inscrits app:qui
    App\Command\CommandeQui:
       arguments:
           $token: '%env(TOKEN)%'
           $botId: '%env(BOT_ID)%'

