<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6wbugBy\srcApp_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6wbugBy/srcApp_KernelDevContainer.php') {
    touch(__DIR__.'/Container6wbugBy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevContainer::class, false)) {
    \class_alias(\Container6wbugBy\srcApp_KernelDevContainer::class, srcApp_KernelDevContainer::class, false);
}

return new \Container6wbugBy\srcApp_KernelDevContainer([
    'container.build_hash' => '6wbugBy',
    'container.build_id' => '89ec5e1a',
    'container.build_time' => 1621439159,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6wbugBy');
