<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4ICQPxV\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4ICQPxV/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4ICQPxV.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4ICQPxV\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4ICQPxV\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4ICQPxV',
    'container.build_id' => 'da9e6a41',
    'container.build_time' => 1575532329,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4ICQPxV');
