<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hozcKr8' shared service.

return $this->privates['.service_locator.hozcKr8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'u' => ['privates', '.errored..service_locator.hozcKr8.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.hozcKr8": it references class "App\\Entity\\User" but no such service exists.'],
], [
    'u' => 'App\\Entity\\User',
]);
