<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NJg9zp6' shared service.

return $this->privates['.service_locator.NJg9zp6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'exception' => ['privates', '.errored..service_locator.NJg9zp6.Symfony\\Component\\Debug\\Exception\\FlattenException', NULL, 'Cannot autowire service ".service_locator.NJg9zp6": it references class "Symfony\\Component\\Debug\\Exception\\FlattenException" but no such service exists.'],
], [
    'exception' => 'Symfony\\Component\\Debug\\Exception\\FlattenException',
]);
