<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AccueilController::setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\AdminController::setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\CalendrierController::setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\ContactController::setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\ExceptionController::showAction' => ['privates', '.service_locator.NJg9zp6', 'get_ServiceLocator_NJg9zp6Service.php', true],
    'App\\Controller\\ExceptionController::showException' => ['privates', '.service_locator.NJg9zp6', 'get_ServiceLocator_NJg9zp6Service.php', true],
    'App\\Controller\\JeuxController::setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\ParentController::setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\SecurityController::checkPassword' => ['privates', '.service_locator.jmvbEvf', 'get_ServiceLocator_JmvbEvfService.php', true],
    'App\\Controller\\SecurityController::connecte' => ['privates', '.service_locator.jmvbEvf', 'get_ServiceLocator_JmvbEvfService.php', true],
    'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.iP8eVIx', 'get_ServiceLocator_IP8eVIxService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.jmvbEvf', 'get_ServiceLocator_JmvbEvfService.php', true],
    'App\\Controller\\SecurityController::newUser' => ['privates', '.service_locator.jmvbEvf', 'get_ServiceLocator_JmvbEvfService.php', true],
    'App\\Controller\\SecurityController::resetPassword' => ['privates', '.service_locator.ccM2MGC', 'get_ServiceLocator_CcM2MGCService.php', true],
    'App\\Controller\\SecurityController::setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\AccueilController:setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\AdminController:setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\CalendrierController:setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\ContactController:setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\ExceptionController:showAction' => ['privates', '.service_locator.NJg9zp6', 'get_ServiceLocator_NJg9zp6Service.php', true],
    'App\\Controller\\ExceptionController:showException' => ['privates', '.service_locator.NJg9zp6', 'get_ServiceLocator_NJg9zp6Service.php', true],
    'App\\Controller\\JeuxController:setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\ParentController:setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
    'App\\Controller\\SecurityController:checkPassword' => ['privates', '.service_locator.jmvbEvf', 'get_ServiceLocator_JmvbEvfService.php', true],
    'App\\Controller\\SecurityController:connecte' => ['privates', '.service_locator.jmvbEvf', 'get_ServiceLocator_JmvbEvfService.php', true],
    'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.iP8eVIx', 'get_ServiceLocator_IP8eVIxService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.jmvbEvf', 'get_ServiceLocator_JmvbEvfService.php', true],
    'App\\Controller\\SecurityController:newUser' => ['privates', '.service_locator.jmvbEvf', 'get_ServiceLocator_JmvbEvfService.php', true],
    'App\\Controller\\SecurityController:resetPassword' => ['privates', '.service_locator.ccM2MGC', 'get_ServiceLocator_CcM2MGCService.php', true],
    'App\\Controller\\SecurityController:setUser' => ['privates', '.service_locator.hozcKr8', 'get_ServiceLocator_HozcKr8Service.php', true],
], [
    'App\\Controller\\AccueilController::setUser' => '?',
    'App\\Controller\\AdminController::setUser' => '?',
    'App\\Controller\\CalendrierController::setUser' => '?',
    'App\\Controller\\ContactController::setUser' => '?',
    'App\\Controller\\ExceptionController::showAction' => '?',
    'App\\Controller\\ExceptionController::showException' => '?',
    'App\\Controller\\JeuxController::setUser' => '?',
    'App\\Controller\\ParentController::setUser' => '?',
    'App\\Controller\\SecurityController::checkPassword' => '?',
    'App\\Controller\\SecurityController::connecte' => '?',
    'App\\Controller\\SecurityController::forgottenPassword' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\SecurityController::newUser' => '?',
    'App\\Controller\\SecurityController::resetPassword' => '?',
    'App\\Controller\\SecurityController::setUser' => '?',
    'App\\Controller\\AccueilController:setUser' => '?',
    'App\\Controller\\AdminController:setUser' => '?',
    'App\\Controller\\CalendrierController:setUser' => '?',
    'App\\Controller\\ContactController:setUser' => '?',
    'App\\Controller\\ExceptionController:showAction' => '?',
    'App\\Controller\\ExceptionController:showException' => '?',
    'App\\Controller\\JeuxController:setUser' => '?',
    'App\\Controller\\ParentController:setUser' => '?',
    'App\\Controller\\SecurityController:checkPassword' => '?',
    'App\\Controller\\SecurityController:connecte' => '?',
    'App\\Controller\\SecurityController:forgottenPassword' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\SecurityController:newUser' => '?',
    'App\\Controller\\SecurityController:resetPassword' => '?',
    'App\\Controller\\SecurityController:setUser' => '?',
]));
