<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ExceptionController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bundle/Controller/ExceptionController.php';
include_once \dirname(__DIR__, 4).'/src/Controller/ExceptionController.php';

return $this->services['App\\Controller\\ExceptionController'] = new \App\Controller\ExceptionController(($this->services['twig'] ?? $this->getTwigService()));
