<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ludotheque extends \App\Entity\Ludotheque implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'fullnom', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'nomComplet', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'img', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'but', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'ppe', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'nbjmin', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'nbjmax', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'nbJoueurs', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'imgNbJoueurs', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'dureemin', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'dureemax', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'rateSt', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'rateTa', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'rateCh', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'rateCo', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'dominance', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'difficulte'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'fullnom', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'nomComplet', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'img', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'but', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'ppe', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'nbjmin', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'nbjmax', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'nbJoueurs', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'imgNbJoueurs', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'dureemin', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'dureemax', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'rateSt', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'rateTa', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'rateCh', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'rateCo', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'dominance', '' . "\0" . 'App\\Entity\\Ludotheque' . "\0" . 'difficulte'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ludotheque $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullnom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullnom', []);

        return parent::getFullnom();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullnom(?string $fullnom): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullnom', [$fullnom]);

        return parent::setFullnom($fullnom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomComplet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomComplet', []);

        return parent::getNomComplet();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomComplet(?string $fullnom): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomComplet', [$fullnom]);

        return parent::setNomComplet($fullnom);
    }

    /**
     * {@inheritDoc}
     */
    public function getImg(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImg', []);

        return parent::getImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setImg(string $img): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImg', [$img]);

        return parent::setImg($img);
    }

    /**
     * {@inheritDoc}
     */
    public function getBut(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBut', []);

        return parent::getBut();
    }

    /**
     * {@inheritDoc}
     */
    public function setBut(string $but): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBut', [$but]);

        return parent::setBut($but);
    }

    /**
     * {@inheritDoc}
     */
    public function getPpe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPpe', []);

        return parent::getPpe();
    }

    /**
     * {@inheritDoc}
     */
    public function setPpe(string $ppe): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPpe', [$ppe]);

        return parent::setPpe($ppe);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbjmin(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbjmin', []);

        return parent::getNbjmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbjmin(int $nbjmin): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbjmin', [$nbjmin]);

        return parent::setNbjmin($nbjmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbjmax(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbjmax', []);

        return parent::getNbjmax();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbjmax(int $nbjmax): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbjmax', [$nbjmax]);

        return parent::setNbjmax($nbjmax);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbJoueurs(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbJoueurs', []);

        return parent::getNbJoueurs();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbJoueurs(?string $nbJoueurs): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbJoueurs', [$nbJoueurs]);

        return parent::setNbJoueurs($nbJoueurs);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgNbJoueurs(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgNbJoueurs', []);

        return parent::getImgNbJoueurs();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgNbJoueurs(?string $imgNbJoueurs): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgNbJoueurs', [$imgNbJoueurs]);

        return parent::setImgNbJoueurs($imgNbJoueurs);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureemin(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureemin', []);

        return parent::getDureemin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureemin(int $dureemin): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureemin', [$dureemin]);

        return parent::setDureemin($dureemin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureemax(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureemax', []);

        return parent::getDureemax();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureemax(int $dureemax): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureemax', [$dureemax]);

        return parent::setDureemax($dureemax);
    }

    /**
     * {@inheritDoc}
     */
    public function getRateSt(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRateSt', []);

        return parent::getRateSt();
    }

    /**
     * {@inheritDoc}
     */
    public function setRateSt(int $rateSt): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRateSt', [$rateSt]);

        return parent::setRateSt($rateSt);
    }

    /**
     * {@inheritDoc}
     */
    public function getRateTa(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRateTa', []);

        return parent::getRateTa();
    }

    /**
     * {@inheritDoc}
     */
    public function setRateTa(int $rateTa): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRateTa', [$rateTa]);

        return parent::setRateTa($rateTa);
    }

    /**
     * {@inheritDoc}
     */
    public function getRateCh(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRateCh', []);

        return parent::getRateCh();
    }

    /**
     * {@inheritDoc}
     */
    public function setRateCh(int $rateCh): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRateCh', [$rateCh]);

        return parent::setRateCh($rateCh);
    }

    /**
     * {@inheritDoc}
     */
    public function getRateCo(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRateCo', []);

        return parent::getRateCo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRateCo(int $rateCo): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRateCo', [$rateCo]);

        return parent::setRateCo($rateCo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDominance(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDominance', []);

        return parent::getDominance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDominance(?bool $dominance): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDominance', [$dominance]);

        return parent::setDominance($dominance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDifficulte(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDifficulte', []);

        return parent::getDifficulte();
    }

    /**
     * {@inheritDoc}
     */
    public function setDifficulte(?string $difficulte): \App\Entity\Ludotheque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDifficulte', [$difficulte]);

        return parent::setDifficulte($difficulte);
    }

}
